name: Deploy React App to Amazon Linux EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest  # GitHub Actions runner (not EC2)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies and build React app
      run: |
        npm ci
        npm run build

    - name: Upload build folder via rsync over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Ensure target directory exists
          mkdir -p /var/www/react-app

          # Create a temp folder for upload
          rm -rf ~/upload-react && mkdir ~/upload-react
    - name: Copy build folder using rsync
      run: |
           rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/react-app
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}

    - name: Restart Nginx on EC2 (Amazon Linux specific)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo systemctl restart nginx
